-- 코드를 입력하세요
SELECT YEAR, MONTH, GENDER, COUNT(DISTINCT USER_ID) AS USERS
  FROM (SELECT A.USER_ID, A.GENDER
             , EXTRACT(YEAR FROM SALES_DATE) AS YEAR
             , EXTRACT(MONTH FROM SALES_DATE) AS MONTH
          FROM USER_INFO A
             , ONLINE_SALE B
         WHERE A.USER_ID = B.USER_ID
           AND A.GENDER IS NOT NULL)
 GROUP BY YEAR, MONTH, GENDER
 ORDER BY YEAR, MONTH, GENDER