-- -- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
  FROM (
        SELECT INS.ANIMAL_ID, INS.NAME
          FROM ANIMAL_INS INS
               LEFT JOIN ANIMAL_OUTS OUTS
                      ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
         WHERE OUTS.ANIMAL_ID IS NOT NULL
         ORDER BY ROUND(MONTHS_BETWEEN(OUTS.DATETIME, INS.DATETIME)) DESC               
       )
 WHERE ROWNUM <= 2;


