-- 코드를 입력하세요
SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH
     , CAR_ID
     , COUNT(*) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE CAR_ID IN (SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                   WHERE START_DATE BETWEEN TO_DATE('20220801','YYYYMMDD') AND TO_DATE('20221031','YYYYMMDD')
                   GROUP BY CAR_ID
                  HAVING COUNT(*) >= 5)
   AND START_DATE BETWEEN TO_DATE('20220801','YYYYMMDD') AND TO_DATE('20221031','YYYYMMDD')
 GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
HAVING COUNT(*) > 0
 ORDER BY MONTH ASC, CAR_ID DESC