-- 코드를 입력하세요
SELECT CAR_ID, CAR_TYPE, FEE
  FROM (SELECT A.CAR_ID
             , A.CAR_TYPE
             , A.DAILY_FEE * 30 * ((100 - B.DISCOUNT_RATE) / 100) AS FEE
          FROM CAR_RENTAL_COMPANY_CAR A
               INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
                       ON A.CAR_TYPE = B.CAR_TYPE
         WHERE A.CAR_ID NOT IN (SELECT CAR_ID
                                  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                                 WHERE TO_CHAR(END_DATE,'YYYYMMDD') > '20221031' AND TO_CHAR(START_DATE,'YYYYMMDD') < '20221201')
           AND A.CAR_TYPE IN ('세단','SUV')
           AND B.DURATION_TYPE = '30일 이상') T1
 WHERE T1.FEE >= 500000 AND T1.FEE < 2000000
 ORDER BY T1.FEE DESC, T1.CAR_TYPE, T1.CAR_ID DESC