-- 코드를 입력하세요
SELECT TIME.HOUR, COUNT(OUTS.DATETIME) AS COUNT
  FROM (
        SELECT LEVEL-1 AS HOUR FROM DUAL CONNECT BY LEVEL <= 24
       ) TIME
       LEFT JOIN ANIMAL_OUTS OUTS
              ON TIME.HOUR = TO_CHAR(OUTS.DATETIME,'HH24')
 GROUP BY TIME.HOUR
 ORDER BY TIME.HOUR;