-- 코드를 입력하세요
SELECT MAX(TO_CHAR(A.SALES_DATE,'YYYY')) AS YEAR
     , MAX(TO_NUMBER(TO_CHAR(A.SALES_DATE,'MM'))) AS MONTH
     , COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS
     , ROUND(COUNT(DISTINCT A.USER_ID) / (SELECT COUNT(USER_ID) 
                                            FROM USER_INFO 
                                           WHERE TO_CHAR(JOINED,'YYYY') = '2021'), 1) AS PUCHASED_RATIO
  FROM ONLINE_SALE A
       INNER JOIN USER_INFO B
               ON A.USER_ID = B.USER_ID
              AND TO_CHAR(B.JOINED,'YYYY') = '2021'
 GROUP BY TO_CHAR(A.SALES_DATE,'YYYYMM')
 ORDER BY YEAR, MONTH