-- 코드를 입력하세요
SELECT A.PRODUCT_CODE
     , SUM(B.SALES_AMOUNT) * MAX(A.PRICE) AS SALES
  FROM PRODUCT A
     , OFFLINE_SALE B
 WHERE B.PRODUCT_ID = A.PRODUCT_ID
 GROUP BY A.PRODUCT_CODE
 ORDER BY SALES DESC, A.PRODUCT_CODE;