-- 코드를 입력하세요
-- 방법1
-- SELECT NAME
--   FROM (SELECT NAME FROM ANIMAL_INS ORDER BY DATETIME)
--  WHERE ROWNUM < 2;
  
-- 방법2
SELECT NAME
  FROM ANIMAL_INS
 WHERE DATETIME = (SELECT MIN(DATETIME) FROM ANIMAL_INS);